### ISSUE TITLE
Suggestion: Crafttweaker support

### ISSUE THREAD

**Issue by Guinaro** [Epoxide-Software/Enchanting-Plus#108]
Whenever the 1.12 version hits I certainly would love some crafttweaker support to mess with enchantments.
E.g. 
- removing certain enchantments from game
- prevent enchantments on certain items
- prevent enchantments to be able to be player made; limit on full enchantment or from or to certain levels.
- ability to create more levels for enchantments (where applicable)
- ability to remove levels from enchantments
- enchantment stages
- updates reflected in JEI

Guinaro

**Comment by darkhax** [comment]
It doesn't really make sense for Enchanting Plus to handle that aspect of tweaking the game, and I think CraftTweaker would be a better mod for doing things like removing enchantments from the game, With that said, aspects of this mod can be configured in a reasonable way, and I think those should have CrT support. The latest 1.12.2 alphas have the ability to blacklist items from being used in the table, and enchantments from being available. As the controls for this mod get better, I hope to integrate more CrT support in the future.

Several API changes have also been made which would allow the enchantments in the advanced enchantment table to be controlled using Game Stages through an add on.
