### ISSUE TITLE
Non-Fatal Crash with some modded items

### ISSUE THREAD

**Issue by BrisingrAerowing** [Epoxide-Software/Enchanting-Plus#110]
[Crash Log](https://gist.github.com/BrisingrAerowing/4c455e2080dcc0d503965f143e0e91ef)

Trying the 1.12.2 alpha v5.0.156 (from the MCModDev Maven) and this happened when I put a Supremium helmet into the table. It also duped the helmet. (I have VanillaFix, which is what alerted me to the crash).

I noticed the code has changed, and from the diff I think `enchantment.type` was null for some reason (probably a mod not registering something correctly).

**Comment by BrisingrAerowing** [comment]
I just checked the MC source, and `enchantment.type` is Nullable. So there needs to be a null check for that.

**Comment by darkhax** [comment]
It's weird that this would be an issue, since vanilla (or a forge patch) is doing the same code without a null check on this. I've made a change which uses the existing code, which should solve this. I am planning to revise this code in the future so if it still has issues let me know.
