### ISSUE TITLE
[1.12.2] Crash

### ISSUE THREAD

**Issue by TheSnowyChickens** [Epoxide-Software/Enchanting-Plus#111]
Hi,
you can see in the picture my more white MC screen, this is a crash (I think)

I just pressed the "no changes have been made" button and then RIP.
![grafik](https://user-images.githubusercontent.com/29357962/45793169-1eee1780-bc91-11e8-8fe9-7e416f4bebe0.png)

Ps: MC don't created a crash log, I closed the game via task manager.
I have only the latest logs: 
[2018-09-20-1.log](https://github.com/Epoxide-Software/Enchanting-Plus/files/2399438/2018-09-20-1.log)

MC: 1.12.2
EP: your first Beta (1.12.2 - 5.0.163)
Forge: 2759
Other mods: only JEI and the required Bookshelf Lib (version 2.3.559)

**Comment by darkhax** [comment]
I believe I have fixed this issue, but I can't bee too sure since it is hard to replicate it to begin with. The new version (5.0.164) can be found [here](https://maven.mcmoddev.com/net/darkhax/eplus/EnchantingPlus-1.12.2/5.0.164/EnchantingPlus-1.12.2-5.0.164.jar). I will be uploading this version to Curse in a few moments as well, but they take a while to approve changes.

**Comment by darkhax** [comment]
After looking into the issue further, it seems I did actually fix it when I thought I did earlier, however the version on CurseForge (5.0.163) is not the version I had intended to release, and is an alpha copy from the previous night. The new version (5.0.164) is completely up to date with the latest code and should fix your issue. 

Please note that the change between the intended 163 release and the one that went up on CurseForge included several major updates to how the table stores it's inventory. The older inventory system was never intended to be public, and I have removed 163 from CurseForge. If you have placed any important items in a table using 163, please remove them from the inventory and then break the table block. Once you have done this, you can safely update to 164 and place the table back down.

**Comment by touhouzun** [comment]
So glad that Eplus ver5.0.164 for mc1.12.2 has been uploaded to curseforge:)
"Required Library:Bookshelf"should be added.
Will test it later in an 115-mods environment.
Hope there won't be critical bugs and crashes.
Thanks for all the hardworkings:)
P.S. I'm not very good at English.My living region always prevents me from linking to media.forgecdn.net_(:з)∠)_

**Comment by TheSnowyChickens** [comment]
And the log was my newest log. I deleted all other logs in attention to the time.
