### ISSUE TITLE
Tip window in a weird position on Normal GUI scale

### ISSUE THREAD

**Issue by Lykrast** [Epoxide-Software/Enchanting-Plus#112]
![image](https://user-images.githubusercontent.com/8684850/45804820-6c807980-bcbd-11e8-99e9-3bb0da839de8.png)

As seen here on Normal GUI scale this tooltip window is placed in a very weird and far spot from the gui.

**Comment by touhouzun** [comment]
But there's no issue with [Auto] GUI scale.
Also [Auto] GUI scale is usually bigger than [Normal],I think.
Before the authors fix the issue,use [Auto] GUI scale to protect your eyes:)

**Comment by Lykrast** [comment]
Yes. Also Auto is too big for me so I'm staying on Normal where it's a good size.

**Comment by darkhax** [comment]
Thanks for the reports, Jared has fixed this issue by anchoring it to the side of the gui always. Unfortunately it will still look super weird when you have a high resolution, however this is an issue which affects all modded GUIs, like JEI. I will push a new beta to CurseForge for this in a moment.
