### ISSUE TITLE
Experience points doesn't decrease after enchant

### ISSUE THREAD

**Issue by totyaxy** [Epoxide-Software/Enchanting-Plus#117]
Hi!

As I wrote in curseforge webpage, I noticed this issue in the latest beta version: 1.12.2-5.0.169. The older beta: 1.12.2-5.0.164 version is okay. I didn't try any other version of this mod recently.

MC 1.12.2

**Comment by SummitSummit** [comment]
Yeah, I'm getting this too.  I can fully enchant all my gear, I only have to have the required experience for an enchant.  Enchanting doesn't actually take my Exp away.

**Comment by totyaxy** [comment]
This problem present in latest (alpha) version:

EnchantingPlus-1.12.2-5.0.173.jar

**Comment by darkhax** [comment]
This issue should be fixed in the next alpha.
