### ISSUE TITLE
Blacklist enchantment id not working

### ISSUE THREAD

**Issue by deathzero021** [Epoxide-Software/Enchanting-Plus#122]
If I type in any integer into the list and launch Minecraft, the config file completely resets to default (all settings reset). So basically blacklisting enchantments doesn't work. 

MC version 1.10.2
EP version 1.0.118
Forge 12.18.3.2422

**Comment by darkhax** [comment]
Hello, the blacklist does not use integers for IDs. They use named IDs, similar to items, blocks, entities, biomes, and so on.

**Comment by deathzero021** [comment]
Named ID's has the same affect. For example, typing in **minecraft:mending** into the list will also result in the config file resetting to defaults.

**Comment by deathzero021** [comment]
Oh, I see. I did not realize it was that strict. I got it working now. Thank you.
