### ISSUE TITLE
Mending??

### ISSUE THREAD

**Issue by DubstepMLGpro2** [Epoxide-Software/Enchanting-Plus#138]
i cant seem to enchant anything with mending there is no option to do so and i did not see anything in the config about it. is there just no mending for this mod?

**Comment by Darkhax** [comment]
Mending is considered a "treasure" enchantment by vanilla, and is not normally obtainable via enchanting. With this mod you need to place "precious" blocks under the table in a 3x3. A precious block is any block that can be used for a beacon base block. I believe it also needs to be day time.
