### ISSUE TITLE
Infinite XP abuse with Magical crops equipment

### ISSUE THREAD

**Issue by DisonGo** [Epoxide-Software/Enchanting-Plus#142]
Enchanting Plus 4.0.0.74-beta
 Magical Crops 4.0.0-full-beta
 1.7.10 modpack
If you try to enchant Magical crops armor(Zivicio for example) to Fire, Blast, Projectile protections (up to 3 level (one by one, not to 3 lvl at once)) and some other enchantments you'll gain levels instead of consuming them
1 to 3d fire protection ex.: https://imgur.com/a/s9cXvNV
Same  things happens with Zivicio tools: https://imgur.com/a/UjDBGaD
To be honest it's a very big xp abuse

**Comment by Darkhax** [comment]
https://www.howoldisminecraft1710.today/
