### ISSUE TITLE
[Suggestion] Add Apotheosis' Enchantments & Limits

### ISSUE THREAD

**Issue by DizzyDJW** [Epoxide-Software/Enchanting-Plus#155]
I'd love to see Apotheosis get some love as it's popular in many modpacks and I added this mod to most for that customizability. It'd be great to be able to have the caps that Apotheosis offers if it's in the same modpack.

If that kind of compatibility is difficult then maybe just some config for enchantment limits.

**Comment by Darkhax** [comment]
There are no plans for apotheosis support. There are other tools available for changing the max levels of enchantments.
