### ISSUE TITLE
1.15.2 support

### ISSUE THREAD

**Issue by infernalspectre** [Epoxide-Software/Enchanting-Plus#162]
Any information on whether or not this mod works with the newest version of Minecraft?

I love this mod and wanted to use it with a new server I'm setting up.

**Comment by Darkhax** [comment]
No this mod has not been updated to the newest version. Forge mods should always be assumed to be broken with each update of the game. An update will happen eventually but I do not give ETAs.

**Comment by infernalspectre** [comment]
Thank you for the response. I totally understand and appreciate the work
you do.
