### ISSUE TITLE
Is it possible to turn on disenchantment option?

### ISSUE THREAD

**Issue by Andrey08083** [Epoxide-Software/Enchanting-Plus#167]
Is it possible to turn on disenchantment option? Because in previous versions of that mod disenchantment function has been enabled by default earlier, but, nowadays, I can't find how to enable disenchantment function. Can you help me with that issue?

**Comment by ChrisLTheNerd** [comment]
You can disenchantment things that haven't lost durability, but it won't refund you for some reason.
