### ISSUE TITLE
repairing items without using the repair enchantment 1.12.2

### ISSUE THREAD

**Issue by EgorimM** [Epoxide-Software/Enchanting-Plus#186]
In previous versions of the mod, there was a function to repair an item without using a repair tool. in version 1.7.10, you could just put a broken item that was enchanted and a button appeared under the enchant button. But in new versions of this mod, this function is not present since 1.9.0 - 1.12.2. Has it been removed? What for? Is there a way to get her back?

**Comment by Darkhax** [comment]
Yes the function was removed. The anvil exists now, and so do many other features for repairing tools.

**Comment by EgorimM** [comment]
But it was helpful. Ok.
