### ISSUE TITLE
1.16.5 zip?

### ISSUE THREAD

**Issue by Ike-l** [Epoxide-Software/Enchanting-Plus#187]
What's with the 1.16.5 zip file? Is it supposed to be jar? should i convert it over?

**Comment by Darkhax** [comment]
This mod does not have a 1.16.5 version at this time. The only official download source for this mod is [CurseForge](https://www.curseforge.com/minecraft/mc-mods/enchanting-plus/files). Any other website is likely trying to trick you into viewing their ads or installing malware.

**Comment by Ike-l** [comment]
And I’m saying the zip is on curse forge

**Comment by democat3457** [comment]
but there isn't any zip on curseforge, what's the link to the file?

**Comment by democat3457** [comment]
ohhhh i see what you mean. https://www.curseforge.com/minecraft/mc-mods/enchanting-plus/files/742183

please check the game version on the file. :)

**Comment by Darkhax** [comment]
Yeah, that's a file from 8 years ago. Not for MC 1.16.5.
