### ISSUE TITLE
IDEA: Treasure Enchantments Aquiring

### ISSUE THREAD

**Issue by evib986** [Epoxide-Software/Enchanting-Plus#191]
**This is my idea of how you should get treasure enchantments:**

1. I think that you should have an enchanter villager (that will get it's profession from the advanced enchanting table). The enchanter villager will sell enchanting related items and **only** on his final trades he will sell **a** treasure enchant.

OR

2. Add a "market" block (still haven't thought of a proper name) like Farming for blockheads block that will sell most items from the mod and treasure enchantments. Keep in mind this is the easiest way I am pitching and don't think it's that good.

OR

3. Add a "market" block (still haven't thought of a proper name) like Farming for blockheads block that will sell most items from the mod and treasure enchantments. But this time it will be crafted from items you trade for excessively with the enchanter villager. Therefore being the hardest way of getting treasure enchantments and combining both ideas.

**Comment by Darkhax** [comment]
Treasure enchantments are already available. Fill the bottom 3x3 with precious materials (Valid beacon block bases) and daylight.
