### ISSUE TITLE
Different books

### ISSUE THREAD

**Issue by qoopdata** [Epoxide-Software/Enchanting-Plus#196]
So, this mod has such different books as: "Tartarite Book", "Prismarine Book" and etc.
How can I use them? 
Or when it will be able to use them?
![image](https://user-images.githubusercontent.com/110809079/201744029-2a5098fa-11e6-4284-bd5f-50f5471a44c6.png)

**Comment by Darkhax** [comment]
These variants were primarily added for modpacks and integration with other mods. You can add recipes for them yourself or use commands to spawn them in, however they're purely decorative and not fully implemented. There is no ETA on when they will be finished, or if they will be included in future updates.
