### ISSUE TITLE
Using non-vanilla table breaks XP

### ISSUE THREAD

**Issue by qreeves** [Epoxide-Software/Enchanting-Plus#48]
In 1.10.2, when using the non-vanilla table, any XP the player gets after that point is not added resulting in them getting stuck at a specific level. It seems the only way to fix this is remove all levels from a player.
- Get some XP (make some coal and mine it)
- Use the eplus table to enchant or repair
- Try to get some more XP (make some coal and mine it)
- No more XP is added to the player
- Type /xp -nL (where n is current level plus one)
- Try to get some more XP (make some coal and mine it)
- XP is added as normal again

**Comment by PCThrow** [comment]
Is there a way to fix this problem w/o having to bug the admins of the server?

**Comment by darkhax** [comment]
This bug should be fixed in the 1.12.2 version of the mod.

**Comment by qreeves** [comment]
Necro fix! Thanks for the update.
