### ISSUE TITLE
No levels back

### ISSUE THREAD

**Issue by StaryCZ** [Epoxide-Software/Enchanting-Plus#50]
In previous versions of this mod, when I wanted to take an enchantement out off an item, it would give me level back saying -N levels. But now when I take off an enchantment, is does not give me levels back. Please fix

**Comment by HalfOfAKebab** [comment]
I think getting levels back would be OP. I think you should not get any levels for removing enchantments.

**Comment by lucom** [comment]
I suggest to add a configuration option in addition to `B:allowDisenchanting=true` :
`B:disenchantingGivesXp=true`
Maybe one should be able to configure a factor so that disenchantig won't give all the XP back.

**Comment by darkhax** [comment]
Disenchanting will no longer give the player experience. There are plans to add this feature back through an alternative mechanic in a future version.
