### ISSUE TITLE
Crash with ender io when loading or creating world

### ISSUE THREAD

**Issue by abdullamu** [Epoxide-Software/Enchanting-Plus#61]
Hello

The details is here https://github.com/mezz/JustEnoughItems/issues/704#issuecomment-274305233

Thank you

**Comment by GamerbyDesign** [comment]
I an using Ender IO in my server and it boots fine with both mods in there.

**Comment by darkhax** [comment]
This issue appears to have been fixed in the other relevant mods, but is a confirmed issue with this mod as well.
