### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by lex1975** [Epoxide-Software/Enchanting-Plus#62]
I can not create Pull Request, so I write here.
I translate to Russian EnchantingPlus-1.10.2-4.1.0.115
[ru_RU.zip](https://github.com/Darkhax-Minecraft/Enchanting-Plus/files/752102/ru_RU.zip)

**Comment by darkhax** [comment]
Thank you for translating the mod, unfortunately this was done during a bad time in the development life cycle of the mod. The new language file is different from the one you based yours on. I am going to close this issue for now, but if you want to update your translations I can still include them.
