### ISSUE TITLE
Disabling Repairing in Config Breaks Enchantment Scrolling

### ISSUE THREAD

**Issue by Revvilo** [Epoxide-Software/Enchanting-Plus#68]
A strange bug seems to be caused by disabling repairing, steps to reproduce are;
Step 1 • Set `allowRepairs` to false in the config.
Step 2 • Launch game.
Step 3 • Place item in table and try to scroll down the enchantment list (while in creative.) You should see that you can't scroll through them.
Step 4 • Set an enchantment to any level on the item but don't click enchant. You should now see that you can scroll the enchantments, really odd.

**Comment by darkhax** [comment]
Repairing has been removed in 1.12.2 in favor of the anvil.
