### ISSUE TITLE
[1.10.2] Client Crash with Repair Icon Button

### ISSUE THREAD

**Issue by iAerosoft** [Epoxide-Software/Enchanting-Plus#70]
I tried using the repair button in the advanced enchantment table on pieces of armor from the Block Armor mod but I get this error when I press the button. It disconnects me from the server and the piece of armor disappears. This is the error in the server console. 
https://pastebin.com/q6Shjwsd

**Comment by LucidLethargy** [comment]
I've just experienced the same exact problem on version 115 (latest stable build, there are three new alpha builds but I haven't tried them yet.)

**Comment by darkhax** [comment]
Repairing has been removed in 1.12.2 in favor of the anvil.
