### ISSUE TITLE
Repairs are free

### ISSUE THREAD

**Issue by LucidLethargy** [Epoxide-Software/Enchanting-Plus#75]
For some reason, I'm not seeing any level deduction after using the repairs on my advanced crafting table (version 115 of the mod). It allowed me to repair upwards of 70 levels worth of gear for free. It does cost levels, right? I hope I'm not missing something here... I didn't see anything else in my inventory reduce, so I'm guessing it's levels and it's broken.

**Comment by Mophise** [comment]
Also having this issue in minecraft 1.10.2
Any insight into the cause would be appreciated. For now I'm disabling repairs on my server.

**Comment by darkhax** [comment]
Repairing has been removed in 1.12.2 in favor of the anvil.
