### ISSUE TITLE
Notice: Beta and Bugs

### ISSUE THREAD

**Issue by darkhax** [Epoxide-Software/Enchanting-Plus#85]
Hello everyone o/ 

If you've been keeping up with this project, you will know that I have had some trouble keeping it up to date for versions above 1.8. The 1.8 MC update introduced a lot of new bugs in the code base, and subsequent updates to the game introduced further bugs, and changes to the vanilla enchanting system. Because of this, and several other personal factors, we have not had a reliable version of this mod for quite some time now. 

Things have finally settled down for me, and I am hoping to have a lot more time to work on this project. I am going to be making Enchanting Plus my top priority for the month of November. I am going to be focusing on 1.12.2, and if things go well, I will be releasing many alpha releases, and hopefully have a public release by the end of November.

For the sake of managing time and other resources, I am discontinuing support for all versions prior to 1.12.2. Issues for these older versions have been marked with the old issue label, and they will likely be closed once I am sure I have no direct need for them.

**Comment by spitfire1081** [comment]
Is there any test version of the 1.12.2 version? Any alpha?
I couldn´t find the Mod´s discord anywhere and there is no updates in this fork since 23 Oct 2017.

**Comment by darkhax** [comment]
@spitfire1081 There have been [several alphas](https://maven.mcmoddev.com/net/darkhax/eplus/EnchantingPlus-1.12.2/), however I stopped posting them to Curse because too many people expected alphas to be playable. I am currently focusing a lot of time on my other mods, however there are plans to pick up this project again very soon.

**Comment by spitfire1081** [comment]
@darkhax I understant. But you see... your mod is UNIQUE. There´s nothing like it to able us to edit the enchantment mechanism. We will really appreciate when you finnally update it to 1.12.2. Thank you for your effort.

**Comment by Spenny519** [comment]
how do I get an alpha version to play with?

**Comment by Thetawaves666** [comment]
Sorry to bother, but there will be in any close future, a 1.12.2 ver coming?

**Comment by darkhax** [comment]
All the issues on this roadmap have been resolved. Stay tune for further announcements.
