### ISSUE TITLE
Repairing with EXP

### ISSUE THREAD

**Issue by darkhax** [Epoxide-Software/Enchanting-Plus#91]
One of the older features in this mod is the option to repair enchanted tools using EXP. This feature predates the vanilla mechanics for repairing tools and is now redundant. There are also some compatibility issues with enchanted tools having RF for durability, allowing for extremely effective EXP to RF conversion, which shouldn't be possible. Because of this, I would like to remove the repair option from the enchanting table.

**Comment by darkhax** [comment]
This option has been removed. An alternative block or option may be added in the future to reset Vanilla's limitation on how many tools have been repaired. But the anvil should be used for repairing.

**Comment by esotericdesign** [comment]
Rotten RF sucks balls.
Also, the mod has no sense with repair and EXP refund features removed.
IMHO, of course
